### PR TITLE
Keep the load method private after monkeypatching

### PR DESCRIPTION
**Pull request by russelldavis**
@ptarjan mind reviewing and merging?

### CODE REVIEW

**Comment by ptarjan** [comment]
Looks great. I don't have credentials apparently. /cc @metcalf

**Comment by metcalf** [comment]
Happy to merge! Can you confirm that you were able to run Zeus with this code?

**Comment by metcalf** [comment]
@russelldavis: I just landed an integration test on master that should give us at least some confidence in new code. Can you rebase on master so that this PR will run tests?

**Comment by russelldavis** [comment]
@metcalf done (I've been running into issues building zeus locally, perhaps we can pair on that quickly tomorrow)

**Pull request merged**
