### PR TITLE
a few more fixes to the vagrant code reloading feature

### PR DESCRIPTION
**Pull request by doy**
This just fixes some bugs that we ran into when testing this functionality internally.

### CODE REVIEW

**Comment by doy** [comment]
Any updates on this?

**Comment by latortuga** [comment]
Merged this branch and built it and I'm still getting a panic on start up: https://gist.github.com/latortuga/0216f3c0cf2e11b4ec8b

**Comment by doy** [comment]
cc/ @burke ?

**Comment by doy** [comment]
Any updates on this?

**Comment by metcalf** [comment]
@doy: it looks like we still need to land this before killing off our fork right? If so, is this up to date and ready for a re-review?

**Comment by metcalf** [comment]
@latortuga: that panic looks unrelated to the changes in this diff. This is rebased on upstream and the new integration tests exercise the code that paniced for you.

@doy: This lgtm and matches what we've been running successfully at Stripe for months so I'm pretty confident in it.

**Pull request merged**
