### PR TITLE
Fix zeus rspec to run via ARGV and rspec/autorun

### PR DESCRIPTION
**Pull request by latortuga**
Unfortunately I can't figure out how to build this anymore and I'm on linux. It would be great if someone could cut a build of this and I could test that it works.

### CODE REVIEW

**Comment by metcalf** [comment]
@latortuga: what error do you get when you run `make` on Linux? I thought I'd fixed up the Makefile such that it should be possible to compile on Linux (it just won't create the OS X binaries).

It also appears that requiring `rspec/autorun` isn't playing nicely with the test suite itself.

**Comment by metcalf** [comment]
Happy to try to build something for you if that's helpful but before I shuffle binaries around I figured it'd be worth trying to help make your `make` happy.

**Comment by latortuga** [comment]
```sh
~/go-workspace/src/github.com/burke/zeus$ make
go get github.com/kardianos/govendor
ZEUS_TEST_GEMPATH=/home/drew/go-workspace/src/github.com/burke/zeus/rubygem GO15VENDOREXPERIMENT=1 govendor test +local
go/filemonitor/filemonitor_fsnotify.go:8:2: cannot find package "github.com/fsnotify/fsnotify" in any of:
	/home/drew/go/src/pkg/github.com/fsnotify/fsnotify (from $GOROOT)
	/home/drew/go-workspace/src/github.com/fsnotify/fsnotify (from $GOPATH)
Error: exit status 1
make: *** [test-go] Error 2
```

**Comment by latortuga** [comment]
Tried to resolve this a bit myself:
```sh
drew@artemis:~/go-workspace/src/github.com/burke/zeus$ go get github.com/fsnotify/fsnotify
# golang.org/x/sys/unix
../../../golang.org/x/sys/unix/syscall_solaris.go:38: clen redeclared in this block
	previous declaration at ../../../golang.org/x/sys/unix/syscall_linux.go:817
../../../golang.org/x/sys/unix/syscall_solaris.go:51: ParseDirent redeclared in this block
	previous declaration at ../../../golang.org/x/sys/unix/syscall_linux.go:830
../../../golang.org/x/sys/unix/syscall_solaris.go:77: Pipe redeclared in this block
	previous declaration at ../../../golang.org/x/sys/unix/syscall_linux_amd64.go:110
../../../golang.org/x/sys/unix/syscall_solaris.go:91: (*SockaddrInet4).sockaddr redeclared in this block
	previous declaration at ../../../golang.org/x/sys/unix/syscall_linux.go:311
../../../golang.org/x/sys/unix/syscall_solaris.go:105: (*SockaddrInet6).sockaddr redeclared in this block
	previous declaration at ../../../golang.org/x/sys/unix/syscall_linux.go:325
../../../golang.org/x/sys/unix/syscall_solaris.go:120: (*SockaddrUnix).sockaddr redeclared in this block
	previous declaration at ../../../golang.org/x/sys/unix/syscall_linux.go:340
../../../golang.org/x/sys/unix/syscall_solaris.go:146: Getsockname redeclared in this block
	previous declaration at ../../../golang.org/x/sys/unix/syscall_linux.go:525
../../../golang.org/x/sys/unix/syscall_solaris.go:155: ImplementsGetwd redeclared in this block
	previous declaration at ../../../golang.org/x/sys/unix/syscall_linux.go:184
../../../golang.org/x/sys/unix/syscall_solaris.go:159: Getwd redeclared in this block
	previous declaration at ../../../golang.org/x/sys/unix/syscall_linux.go:188
../../../golang.org/x/sys/unix/syscall_solaris.go:180: Getgroups redeclared in this block
	previous declaration at ../../../golang.org/x/sys/unix/syscall_linux.go:201
../../../golang.org/x/sys/unix/syscall_solaris.go:180: too many errors
```

:cry:

**Comment by latortuga** [comment]
Tried a little more after installing golang 1.7.1

```sh
~/go-workspace/src/github.com/burke/zeus$ go version
go version go1.7.1 linux/amd64

~/go-workspace/src/github.com/burke/zeus$ make
go get github.com/kardianos/govendor
# github.com/kardianos/govendor/cliprompt
../../kardianos/govendor/cliprompt/cliPrompt.go:13: import /home/drew/go-workspace/pkg/linux_amd64/github.com/kardianos/govendor/prompt.a: not a package file
# github.com/kardianos/govendor/context
../../kardianos/govendor/context/context.go:18: import /home/drew/go-workspace/pkg/linux_amd64/github.com/kardianos/govendor/internal/pathos.a: not a package file
make: *** [govendor] Error 2

~/go-workspace/src/github.com/burke/zeus$ make clean
rm -rf vagrant/ext/fsevents/build man/build go/zeusversion
rm -rf rubygem/{man,build,pkg,examples,lib/zeus/version.rb,MANIFEST}
rm -rf vagrant/{build,pkg,lib/vagrant-zeus/version.rb,MANIFEST}

~/go-workspace/src/github.com/burke/zeus$ make
mkdir -p go/zeusversion
go get github.com/kardianos/govendor
# github.com/kardianos/govendor/cliprompt
../../kardianos/govendor/cliprompt/cliPrompt.go:13: import /home/drew/go-workspace/pkg/linux_amd64/github.com/kardianos/govendor/prompt.a: not a package file
# github.com/kardianos/govendor/context
../../kardianos/govendor/context/context.go:18: import /home/drew/go-workspace/pkg/linux_amd64/github.com/kardianos/govendor/internal/pathos.a: not a package file
make: *** [govendor] Error 2
```

**Comment by sideshowcoder** [comment]
I think this is superseeded by #618 am I correct on this?

**Comment by sideshowcoder** [comment]
I'm gonna close this as I'm fairly sure #618 fixes this, if I'm wrong please reopen and tell me I'm wrong 😄

**Pull request closed without merging**
