### PR TITLE
Bump version for release

### PR DESCRIPTION
**Pull request by metcalf**
Bumps version to 0.15.6. Since I don't have access to Rubygems, I can't actually release this but bumping the version allows us to deploy it via our internal gem server.

@burke: any objections to me bumping the version as we land changes even if we have no way to release in lock-step? As a consequence, releases on rubygems would have gaps in the version sequence but I don't think that's a problem in practice.

### CODE REVIEW

**Comment by latortuga** [comment]
Provided everything builds nicely I can do builds as I do have rubygems
access! I haven't setup my go tool chain for building which is what has
held up builds in the recent past. Are there release notes for the release
as well?

**Comment by metcalf** [comment]
Happy to add them! For a bit of extra context, I'm in the process of getting us off of our fork at https://github.com/stripe/zeus. As soon as I confirm that current HEAD works for us, I'll ping you with some release notes.

**Comment by metcalf** [comment]
@latortuga: I believe this is ready for release.

**Comment by metcalf** [comment]
For a bit more context, I want to land this which will get Stripe off our private fork and into mainline. If that goes smoothly, I'll land the bevy of other PRs I have out and cut a release for that. I want to separate the two releases to identify any problems with switching to upstream -- hearing from internal users will probably be my best feedback channel for bugs.

**Comment by metcalf** [comment]
I released this internally and it has been going well. I'm blocking on incrementing the version again for landing a bunch more code. I'm going to go ahead and land this, followed by a series of other PRs and another bump to 0.15.7. 

@latortuga: whenever you get a chance you can publish as many of the minor versions as you feel appropriate. If you don't like me incrementing the version number out-of-sync with publishing then I'm going to have to do separately versioned internal releases 😢 .

**Comment by latortuga** [comment]
No problem, I'll try to get the intermediate versions built. I have to do it when I'm on my laptop (Mac) which I don't use nearly as much as my linux box these days.

**Pull request merged**
