### PR TITLE
Vagrant code reloading

### PR DESCRIPTION
**Pull request by doy**
This pull request adds support for a new kind of file monitor which listens on the network for something else to feed it changed files, and also adds a Vagrant plugin which uses the existing file monitors to watch for changed files and feed them over the network. The goal here is to be able to run zeus inside a Vagrant VM, and then run `vagrant zeus-file-monitor` from outside the VM, and assuming that ports are opened properly in your Vagrant configuration, things should just work. This pull request isn't quite ready to merge (it has no documentation yet, for instance, and I'd like to do a bit more testing), but it does work, and I wanted to get some feedback about the general direction of things before polishing it up.

Steps to run:
- In your Vagrantfile, `config.vm.network "forwarded_port", guest: 7123, host: 7123, protocol: 'tcp', host_ip: '127.0.0.1'`, and configure a `synced_folder` which contains your zeus-using project
- Run `vagrant plugin install /path/to/vagrant/plugin/pkg/vagrant-zeus-0.15.4.gem`
- Inside Vagrant, `export ZEUS_NETWORK_FILE_MONITOR_PORT=7123` and run zeus
- Outside Vagrant, run `vagrant zeus-file-monitor`

A few notes:
- I believe that this works on OSX, but I haven't done an extensive amount of testing there (I personally develop on Linux).
- This just ignores any files that don't exist on a Vagrant synced folder - this seems reasonable, since it's not really clear how to detect that sort of thing without a lot of extra complexity, but it still might be surprising.
- Vagrant requires Ruby 2+, but zeus is supposed to work with Ruby 1.9+. I'm not sure what the best way to handle this in the build system is.

Let me know what you think!

### CODE REVIEW

**Comment by latortuga** [comment]
First, thanks so much for this ambitious contribution! :+1: x :100: 

Seeing as how I haven't cut a release in months, I'm going to merge this and go live with it. If we find any issues we can always fix em up later. I've bumped zeus support to ruby 2.0+ as 1.9.3 isn't even officially supported anymore.

**Comment by latortuga** [comment]
@doy unfortunately, I'm having issues getting zeus to build on master now. Any chance you can get a golang environment setup and try to troubleshoot a bit?

**Comment by doy** [comment]
What kinds of issues are you running into? You might need to do a `make clean` or `git clean` or something, since I shuffled things around in the build process a bit, but it's building fine for me locally.

**Comment by latortuga** [comment]
To be more precise, I'm having issue with the built gem, zeus crashes on start. Here's my rc build:

https://www.dropbox.com/s/ityddamsevucna9/zeus-0.15.5.rc1.gem?dl=0

**Comment by latortuga** [comment]
Gem built on mac, testing on mac. Haven't tested on linux yet.

**Comment by latortuga** [comment]
Same result on Ubuntu, immediate panic on startup. Not sure if my golang-fu is good enough to track this down. Here's a gist of the panic output: https://gist.github.com/latortuga/0814bf8f64317986f982

**Comment by doy** [comment]
Hey, sorry I haven't gotten back to you yet! Some things came up at work, and I've been pretty busy for the past few weeks. I did some digging today, and as far as I can tell, it isn't related to any of the code I wrote. It looks like a race condition in the terminal drawing code for tty mode, although it's unclear exactly where. In my testing it seems to crash or not pretty arbitrarily depending on the version of go I used to build it, where I add `println`s, etc. I didn't notice it during my initial development due to a combination of our main app explicitly disabling tty mode due to earlier issues like this and just random luck about how it happened to build. I'll keep poking at it for a bit, but I'm not sure how far I'll be able to get - I'm pretty new at go too.

**Comment by doy** [comment]
For instance: http://paste.tozt.net/2015-11-30ddaBAxCy-zeus-0.15.5.broken.99.gem is a gem built from 6c782e58 (latest master, after my branch was reverted) with go 1.4.1 and ruby 2.1.5p273, which segfaults for me in the exact same way that yours did in your gist. http://paste.tozt.net/2015-11-30HDezkm2i-zeus-0.15.5.working.99.gem is a working version, built entirely identically, except that I added `println("foo")` to line 27 of `ttyutils_linux.go` in the burke/ttyutils dependency. I'm not sure where exactly to go from here - I'm really not familiar with either go or this codebase at all.

**Comment by doy** [comment]
I am pretty interested in getting this code merged though, so do let me know if there's anything specific I can help with.

**Comment by latortuga** [comment]
Seems there's a race somewhere. @burke any chance you could try to take a look at this? I tried to look into this issue a month or so back and I found that I just don't know enough about golang tools or panic traces to be able to debug efficiently.

**Comment by burke** [comment]
Issue *should* be fixed by 4a8086c5f6e68c3132313740ed135b5cf1661309. Really cool contribution!

**Pull request merged**
