### PR TITLE
Support new Rails 5.1 command structure

### LINKED ISSUE #634: cannot load such file -- rails/commands/console
Hi, after upgrading to rails 5, I can no longer run `zeus console`

I get the following error:

```
/usr/local/bundle/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require': cannot load such file -- rails/commands/console (LoadError)
	from /usr/local/bundle/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `block in require'
	from /usr/local/bundle/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /usr/local/bundle/gems/activesupport-5.1.0/lib/active_support/dependencies.rb:292:in `require'
	from /usr/local/bundle/gems/zeus-0.15.10/lib/zeus/rails.rb:131:in `console'
	from /usr/local/bundle/gems/zeus-0.15.10/lib/zeus.rb:147:in `block in command'
	from /usr/local/bundle/gems/zeus-0.15.10/lib/zeus.rb:134:in `fork'
	from /usr/local/bundle/gems/zeus-0.15.10/lib/zeus.rb:134:in `command'
	from /usr/local/bundle/gems/zeus-0.15.10/lib/zeus.rb:50:in `go'
	from -e:1:in `<main>'
```

Any ideas?

### PR DESCRIPTION
**Pull request by sideshowcoder**
Fixes #634 based on suggestion by @server-monitor

### CODE REVIEW

**Comment by server-monitor** [comment]
That's awesome. I didn't even think about putting in logic to decide between versions > and < 5.1. There's one small typo though on the `run_rails_5_1_or_higer_command` method name. I think you meant `run_rails_5_1_or_higher_command`.

**Comment by sideshowcoder** [comment]
Oh yeah me can't type 👍 thanks for taking a look.

**Comment by iGEL** [comment]
@sideshowcoder Thank you very much for this. Any chance for a new release soon? It's our only blocker for the Rails 5.1 update.

**Comment by server-monitor** [comment]
@iGEL It's already released. I tested it a few days ago.

**Comment by sideshowcoder** [comment]
Currently released as pre so yeah use it! :D

**Pull request merged**
