### PR TITLE
Bug 627 pager hangs

### LINKED ISSUE #624: Messing up terminal input buffer
## Description of Problem

Since version 0.15.13 zeus slave commands leave the terminal in a dirty state. Version 0.15.12 seems to work fine on a new project.

## System details

* **`uname -a`**:  Linux max 3.2.0-4-amd64 #1 SMP Debian 3.2.84-1 x86_64 GNU/Linux

* **`ruby -v`**: ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]

* **`rbenv --version`**: rbenv 0.4.0-183-gc18a3f9

## Steps to Reproduce

1) `zeus start` in a new rails project

2) `zeus test` or `zeus server` or any other.

## Observed Behavior

After the tests finish, my keyboard input doesn't show up until I hit enter. The output is then formatted in the wrong way like this:
```
localhost:/tmp/rails/blog$ zeus test
Run options: --seed 23423

# Running:



Finished in 0.003751s, 0.0000 runs/s, 0.0000 assertions/s.

0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
localhost:/tmp/rails/blog$ ^C
                              localhost:/tmp/rails/blog$ ^C
                                                            localhost:/tmp/rails/blog$ app  config     custom_plan.rb  Gemfile       lib  public    README.rdoc  tmp     zeus.json
                                       bin  config.ru  db              Gemfile.lock  log  Rakefile  test         vendor
```

### LINKED ISSUE #627: Pager hangs in debugger console when displaying output via the pager (less)
Zeus v0.15.13

Repeat by:

* configure with `pry` or `byebug`
* insert a `binding.pry` or `byebug` into the code
* start a server with `zeus rails s`
* invoke the code with the debugger call
* at the resulting console prompt issue a `User.all` or some other command that invokes the pager

At the first pager prompt, `:`, nothing will advance to the next page, `Ctrl-C` does not abort.  I have to use `^Z` to suspend the process, then `kill -9 %1` to REALLY kill the process.

Here is `pstree` output, that shows the relationships at the time of the hang:

```
|-+= 84190 tarsa /Applications/Utilities/Terminal.app/Contents/MacOS/Terminal -psn_0_30776664
 | |-+= 84196 root login -pfl tarsa /bin/bash -c exec -la bash /bin/bash
 | | \-+= 84203 tarsa -bash
 | |   \--= 78756 tarsa /Users/tarsa/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zeus-0.15.13/build/zeus-darwin-amd64 s
 | |-+= 84303 root login -pfl tarsa /bin/bash -c exec -la bash /bin/bash
 | | \-+= 84317 tarsa -bash
 | |   \-+= 35104 tarsa /Users/tarsa/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/zeus-0.15.13/build/zeus-darwin-amd64 start
 | |     \-+- 35118 tarsa zeus slave: boot   
 | |       \-+- 35120 tarsa zeus slave: default_bundle   
 | |         |-+- 80577 tarsa zeus slave: development_environment   
 | |         | |-+= 78770 tarsa zeus runner: server   
 | |         | | \-+- 78771 tarsa zeus command: server   
 | |         | |   \--- 79556 tarsa less -R -F -X .      # <---------- pager here
 | |         | \-+- 80597 tarsa zeus slave: prerake   
 | |         |   \--= 72432 tarsa (ruby)
 | |         \-+- 80578 tarsa zeus slave: test_environment   
 | |           \-+- 80598 tarsa zeus slave: test_helper   
 | |             \-+= 79389 tarsa zeus runner: test   
 | |               \-+- 79390 tarsa zeus command: test   
 | |                 \--= 79395 tarsa /usr/local/bin/phantomjs --proxy-type=none --load-images=no --ignore-ssl-errors=yes --ssl-protocol=any /User
```

### LINKED ISSUE #636: After running tests or any zeus command terminal text disappears
After running tests or any zeus commands terminal text disappears. 

screen shot 2017-05-11 at 15 51 37

You can see I typed `zspec` to run my tests. After the test finished I ran the same command but now no text is shown. I have to close out the terminal to be able to see what I type again.

### PR DESCRIPTION
**Pull request by sideshowcoder**
Restore terminal state after exit

fixes #624
fixes #636
fixes #627 by disabling pry paging

- [ ] create pre-release version for testing

### CODE REVIEW

**Comment by sideshowcoder** [comment]
Released as version `0.15.14.pre` ... if everything is fine will make this `0.15.14`

**Comment by typeoneerror** [comment]
@sideshowcoder 😍 where can we send you a tip?

**Comment by typeoneerror** [comment]
Been using it most of the day. No blanks so far!

One `Terminated: 15`

and One:

```
slavenode.go:226: [development_environment] read unix ->: EOF
slavenode.go:226: [test_environment] read unix ->: EOF
```

But I believe those are existing issues.

**Comment by sideshowcoder** [comment]
Yep pretty sure those existed before thanks for testing @typeoneerror. Happy to get this fixed no need to tip but thought is much appreciated :)

**Pull request merged**
